plugins:
  - rubocop-rake
require:
  - rubocop-rspec

AllCops:
  NewCops: disable

Metrics/MethodLength:
  Max: 20

Capybara/RSpec/PredicateMatcher:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5
