name: CI Tests

on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7.5, 3.0.3, 3.2.0, 3.4.4]
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake spec
